name: native_app
description: Islami Jindegi Native App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/images/icons/
  
  fonts:
    - family: bangla/solaimanlipi
      fonts:
        - asset: assets/fonts/solaimanlipi.ttf
    
    - family: bangla/siyamrupali
      fonts:
        - asset: assets/fonts/siyamrupali.ttf
    
    - family: bangla/kalpurush
      fonts:
        - asset: assets/fonts/kalpurush.ttf
    
    - family: arabic/al-qalam
      fonts:
        - asset: assets/fonts/al-qalam-quran-majeed.ttf
    
    - family: arabic/al-qalam-kolkatta
      fonts:
        - asset: assets/fonts/al-qalam-kolkatta-quranic-regular.ttf