name: native_app
description: Islami Jindegi Native App

publish_to: 'none'

version: 5.0.6+101

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # application
  flutter_dotenv: ^5.0.2

  # state management
  flutter_riverpod: ^2.3.10

  # routing
  qlevar_router: ^1.7.1

  # data
  flutter_data: ^1.5.13
  flutter_data_json_api_adapter: ^0.8.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  equatable: ^2.0.5

  # local db
  drift: ^2.10.0
  sqlite3_flutter_libs: ^0.5.13
  json_api: ^5.3.0

  # form
  date_field: ^3.0.2
  dropdown_button2: ^2.3.9
  idkit_inputformatters: ^0.0.1
  easy_debounce: ^2.0.3

  # widgets
  infinite_scroll_pagination: ^4.0.0
  carousel_slider: ^4.1.1
  animated_toggle_switch: ^0.8.0
  just_audio: ^0.9.35
  pdfx: 2.4.0
  # pdfx:
  #   path: /home/musaffa/projects/libraries/packages.flutter/packages/pdfx

  # text
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  flutter_html: '^3.0.0-beta.2'
  inflection3: ^0.5.3+2
  recase: ^4.1.0
  html: ^0.15.2

  # platform
  permission_handler: ^10.2.0
  path_provider: ^2.0.12
  shared_preferences: ^2.0.16
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  connectivity_plus: ^3.0.3
  open_filex: ^4.3.2
  share_plus: ^4.5.3

  # http
  dio: ^5.3.2
  url_launcher: ^6.1.14

  # builder
  json_annotation: ^4.7.0

  # utility
  path: '^1.8.3'
  glob: ^2.1.2

  # extensions
  collection: ^1.16.0

  # islamic
  hijri: ^3.0.0
  hijri_picker:
    git:
      url: https://github.com/musaffa/hijri_picker.git
      ref: pass-weekday-number
  adhan: ^2.0.0-nullsafety.2
  smooth_compass: ^2.0.12

  # app widget
  home_widget: ^0.3.0
  workmanager: ^0.5.1

  # firebase
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4

  # assets
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  transparent_image: ^2.0.0
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.6
  isar_generator: ^3.0.5

  json_serializable: ^6.3.1
  faker: ^2.0.0
  drift_dev: ^2.10.0

  flutter_launcher_icons: "^0.13.1"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/books/
    - assets/db/offline_data_2.sqlite3
    - assets/db/offline_location_1.sqlite3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

    - family: bangla/solaimanlipi
      fonts:
        - asset: assets/fonts/solaimanlipi.ttf

    - family: bangla/siyamrupali
      fonts:
        - asset: assets/fonts/siyamrupali.ttf

    - family: bangla/kalpurush
      fonts:
        - asset: assets/fonts/kalpurush.ttf

    - family: arabic/al-qalam-quran-majeed
      fonts:
        - asset: assets/fonts/al-qalam-quran-majeed.ttf

    - family: arabic/al-qalam-kolkatta
      fonts:
        - asset: assets/fonts/al-qalam-kolkatta-quranic-regular.ttf

    - family: arabic/al-mushaf
      fonts:
        - asset: assets/fonts/al-mushaf-quran.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/logos/logo-icon.png

flutter_native_splash:
  color: "#0a676a"
  image: assets/images/logos/logo-transparent.png
  web: false

  android_12:
    image: assets/images/logos/logo-transparent-android-12.png
